### ISSUE TITLE
Xposed not mentioned in description | does not work on Android 9

### ISSUE THREAD

**Issue by marcdw1289** [binarynoise/AutomaticAdvancedSettingsExpander#2]
Just discovered this on IzzyOnDroid. Nice.

First installed on crDroid Android 8. Once installed I couldn't figure out what do as there was no launcher icon.

Then installed it on Havoc Pie ROM. Received an Xposed/LSPosed notification. Ah, now I saw. That crDroid does not have Xposed. Description/README does not mention it is an Xposed module. Might want to make that clear. Thought it was a standalone utility.

Tests.
**HavocOS, Android 9:**  Not working. The Advanced drop-down is still present.
**/e/OS (LOS-based), Android 10:**  Works.
**crDroid, Android 11:**  Works.
**/e/OS, Android 11:**  Works.

All above using LSPosed 1.8.6.

The device with crDroid Oreo is a multibooter so I'll test on the other ROMs shortly.

**Comment by binarynoise** [comment]
Interesting that my app landed on IzzyOnDroid. I only put into the LSPosed module repo so I am a bit surprised that it shows up on IzzyOnDroid.

I'll probably add it to the readme.
It has no activity because it's an xposed module without UI or settings, but LSPosed should notify you that you installed an xposed module.

Regarding HavocOS and android 9, do other android 9 ROMs work? My oldes test device has Android 11, so I can't test myself.
Do you find error messages in the LSPosed logs? It should complain about a class or method not found.

**Comment by marcdw1289** [comment]
I am such a blind old man. Did not realize the module is over a year old. I only paid attention to the date in the F-Droid client, April 9 2023. Apologies for not paying attention.

Been noticing more modules showing up in the client lately. Maybe some third party is submitting things. 


Okay, I see that Havoc Pie doesn't have a required class(?). No worries.


```
Caused by: java.lang.ClassNotFoundException: androidx.preference.PreferenceGroup
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:453)
	at o.a(Unknown Source:20)
	at de.robv.android.xposed.XposedHelpers.findClass(Unknown Source:4)
	... 19 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.preference.PreferenceGroup" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/system/priv-app/Settings/Settings.apk"],nativeLibraryDirectories=[/system/priv-app/Settings/lib/arm64, /system/priv-app/Settings/Settings.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64, /system/lib64, /system/vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 23 more
```

**Comment by binarynoise** [comment]
> Did not realize the module is over a year old.

I think me meant different things with "activity". In the android world an Activity is an UI component. The repo has no activity (in the sense of code changes) because it is rather simple and unlikely to break. 

Yes, the class which I hook and "change" is missing so the module won't work.

I'll look into it to find the correct class for Android 9-

**Comment by binarynoise** [comment]
I updated the module and created a new release:
https://github.com/binarynoise/AutomaticAdvancedSettingsExpander/releases/tag/v2.0

**Comment by marcdw1289** [comment]
Ah, thanks for the tip.
All I get is...

```
04-25 02:31:17.902 20921 20921 D AutomaticSettingsExpand: Hooked androidx.preference.PreferenceGroup
04-25 02:35:15.096 21258 21258 D AutomaticSettingsExpand: Hooked androidx.preference.PreferenceGroup
04-25 02:39:35.311 21665 21665 D AutomaticSettingsExpand: Hooked android.support.v7.preference.PreferenceGroup
04-25 02:42:03.298 21837 21837 D AutomaticSettingsExpand: Hooked androidx.preference.PreferenceGroup
```

Initially I had used MatLog to look for something but found nothing.
Xposed logs showed the module loaded but otherwise nothing else related. As far as I could tell.

**Comment by binarynoise** [comment]
I looked at that Oreo ROM and didn't find anything related. But who uses Oreo any more anyway?
